### ISSUE TITLE
panic: Index out of range

### ISSUE THREAD

**Issue by mattbostock** [retailnext/hllpp#4]
I hit the following panic (just once):

```
panic: runtime error: index out of range

goroutine 29 [running]:
github.com/mattbostock/example/vendor/github.com/retailnext/hllpp.getRegister(0xc420a3a000, 0x263, 0x400, 0x364000000005, 0xc420679e10)
        /go/src/github.com/mattbostock/example/vendor/github.com/retailnext/hllpp/dense.go:46 +0xe5
github.com/mattbostock/example/vendor/github.com/retailnext/hllpp.(*HLLPP).updateRegisterIfBigger(0xc42011e690, 0x100003640)
        /go/src/github.com/mattbostock/example/vendor/github.com/retailnext/hllpp/hllpp.go:127 +0x157
github.com/mattbostock/example/vendor/github.com/retailnext/hllpp.(*HLLPP).Add(0xc42011e690, 0xc420d16060, 0x60, 0x60)
        /go/src/github.com/mattbostock/example/vendor/github.com/retailnext/hllpp/hllpp.go:113 +0x1d5
main.main.func1(0x981b24, 0x16)
        /go/src/github.com/mattbostock/example/internal/test/bench/bench.go:85 +0x26d
created by main.main
        /go/src/github.com/mattbostock/example/internal/test/bench/bench.go:62 +0xbf
```

**Comment by mattbostock** [comment]
Ah, re-read the documentation (godoc comments) and I'm probably hitting this due to concurrent use from multiple goroutines. Closing.
